### ISSUE TITLE
Interested in large updates to the project?

### ISSUE THREAD

**Issue by pmaccamp** [quemb/QMBForm#14]
I'm a huge fan of XLForm for iOS and I appreciate the effort shown here to start recreating it on android.

I've been building out a lot of missing xlform features locally however I've made some breaking changes (mostly renaming of cells to fit a more consistent naming convention) and a lot needs cleanup + tests.  Some of the things I've done so far include
* Validation with support for specifying custom validation classes in annotations
* Segmented controller and spinner cells that follow xlform's selectorOptions and FormOptionsObject pattern with support for specifying primitive value selector options in annotations.
* Inline versions of most cells (horizontal orientation so that the label and value are on the same line)

How interested are you in these changes and what are your current plans for the project?

**Comment by hjanuschka** [comment]
:+1:  from my side!

**Comment by tonimoeckel** [comment]
I'm glad to hear that you'd like to improve this library.  How would you like to proceed with it?

**Comment by pmaccamp** [comment]
Cool - I'll start cleaning up stuff and make a pull request and we can go from there
